# Generated by Django 5.1.3 on 2024-11-13 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='purchase',
            new_name='StockGarden_product_ecd471_idx',
            old_name='StockGarden_product_83960f_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash on Hands', 'Cash on Hands'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(blank=True, default='No Available', null=True, on_delete=django.db.models.deletion.CASCADE, to='StockGarden.product'),
        ),
    ]
