# Generated by Django 5.1.5 on 2025-02-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Cash on Hands', 'Cash on Hands')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Full Payment', 'Full Payment')], db_index=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('logo', models.ImageField(blank=True, upload_to='company/logos/')),
            ],
            options={
                'verbose_name': 'Company',
                'indexes': [models.Index(fields=['name', 'phone_number'], name='StockGarden_name_f91e02_idx')],
            },
        ),
    ]
