# Generated by Django 5.1.5 on 2025-04-28 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StockGarden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='StockGarden.brand'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_categories', to='StockGarden.category'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repair',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='repairdetail',
            name='repair_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='StockGarden.repair'),
        ),
        migrations.AddField(
            model_name='repairinvoice',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairinvoice', to='StockGarden.repair'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['Total_sells'], name='StockGarden_Total_s_0dc15d_idx'),
        ),
        migrations.AddField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='StockGarden.product'),
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StockGarden.product'),
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesinvoice', to='StockGarden.sales'),
        ),
        migrations.AddField(
            model_name='return',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='StockGarden.salesinvoice'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='StockGarden_name_42fbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['product_name'], name='StockGarden_product_8f02af_idx'),
        ),
        migrations.AddIndex(
            model_name='repair',
            index=models.Index(fields=['product_name'], name='StockGarden_product_d87f79_idx'),
        ),
        migrations.AddIndex(
            model_name='repairdetail',
            index=models.Index(fields=['product_name'], name='StockGarden_product_3edf03_idx'),
        ),
        migrations.AddIndex(
            model_name='repairinvoice',
            index=models.Index(fields=['invoice_number'], name='StockGarden_invoice_0bd60d_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['user'], name='StockGarden_user_id_96639d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_number'], name='StockGarden_invoice_9de59a_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_date'], name='StockGarden_return__332b87_idx'),
        ),
    ]
