# Generated by Django 5.1.5 on 2025-04-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(db_index=True, max_length=191, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid_amount',
            field=models.IntegerField(),
        ),
    ]
