# Generated by Django 5.1.3 on 2024-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='expiring_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Hands', 'Cash on Hands'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa'), ('Bank Transfer', 'Bank Transfer')], db_index=True, max_length=255),
        ),
    ]
