# Generated by Django 5.1.5 on 2025-06-17 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StockGarden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='StockGarden_name_4cbcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='StockGarden_name_d234c5_idx'),
        ),
        migrations.AddField(
            model_name='daybook',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='StockGarden.account'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='StockGarden.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='StockGarden.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='StockGarden.brand'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_categories', to='StockGarden.category'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repair',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Customer Name'),
        ),
        migrations.AddField(
            model_name='repairdetail',
            name='repair_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='details', to='StockGarden.repair'),
        ),
        migrations.AddField(
            model_name='repairinvoice',
            name='repair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repairinvoice', to='StockGarden.repair'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['Total_sells'], name='StockGarden_Total_s_0dc15d_idx'),
        ),
        migrations.AddField(
            model_name='return',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='StockGarden.product'),
        ),
        migrations.AddField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='StockGarden.product'),
        ),
        migrations.AddField(
            model_name='sales',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesinvoice', to='StockGarden.sales'),
        ),
        migrations.AddField(
            model_name='return',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='StockGarden.salesinvoice'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='StockGarden.product'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['code'], name='StockGarden_code_1e271e_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type'], name='StockGarden_account_580fc8_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['transaction_date'], name='StockGarden_transac_e8f46a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['entry_type'], name='StockGarden_entry_t_fb94b4_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['payment_method'], name='StockGarden_payment_883949_idx'),
        ),
        migrations.AddIndex(
            model_name='cashbook',
            index=models.Index(fields=['is_bank'], name='StockGarden_is_bank_b91389_idx'),
        ),
        migrations.AddIndex(
            model_name='daybook',
            index=models.Index(fields=['date'], name='StockGarden_date_efbd2f_idx'),
        ),
        migrations.AddIndex(
            model_name='daybook',
            index=models.Index(fields=['transaction_type'], name='StockGarden_transac_d37b8a_idx'),
        ),
        migrations.AddIndex(
            model_name='daybook',
            index=models.Index(fields=['reference_id'], name='StockGarden_referen_e3ef44_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['date'], name='StockGarden_date_d117ba_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account'], name='StockGarden_account_1a3b74_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction_type', 'transaction_id'], name='StockGarden_transac_6f60f5_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='StockGarden_name_42fbbb_idx'),
        ),
        migrations.AddConstraint(
            model_name='profitandloss',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['product_name'], name='StockGarden_product_8f02af_idx'),
        ),
        migrations.AddIndex(
            model_name='repair',
            index=models.Index(fields=['product_name'], name='StockGarden_product_d87f79_idx'),
        ),
        migrations.AddIndex(
            model_name='repairdetail',
            index=models.Index(fields=['product_name'], name='StockGarden_product_3edf03_idx'),
        ),
        migrations.AddIndex(
            model_name='repairinvoice',
            index=models.Index(fields=['invoice_number'], name='StockGarden_invoice_0bd60d_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['user'], name='StockGarden_user_id_96639d_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['invoice_number'], name='StockGarden_invoice_9de59a_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['return_date'], name='StockGarden_return__332b87_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['product'], name='StockGarden_product_776b27_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['transaction_date'], name='StockGarden_transac_029f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['transaction_type'], name='StockGarden_transac_0735e5_idx'),
        ),
    ]
