# Generated by Django 5.1.5 on 2025-07-25 16:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Voucher',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=191, verbose_name='Product Name')),
                ('warranty', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('needs_repair', 'Needs Repair')], default='new', max_length=20)),
                ('description', models.CharField(blank=True, max_length=191, null=True)),
                ('imei', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_imgs/')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to='StockGarden.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_items', to='StockGarden.category')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='StockGarden.purchasevoucher')),
            ],
            options={
                'verbose_name': 'Purchase Item',
                'verbose_name_plural': 'Purchase Items',
            },
        ),
        migrations.CreateModel(
            name='SalesVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Voucher',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('warranty', models.IntegerField(blank=True, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('good', 'Good'), ('needs_repair', 'Needs Repair')], default='new', max_length=20)),
                ('imei', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_items', to='StockGarden.product')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='StockGarden.salesvoucher')),
            ],
            options={
                'verbose_name': 'Sales Item',
                'verbose_name_plural': 'Sales Items',
            },
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesinvoice', to='StockGarden.salesvoucher'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
        migrations.AddIndex(
            model_name='purchasevoucher',
            index=models.Index(fields=['voucher_number'], name='StockGarden_voucher_ce0437_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasevoucher',
            index=models.Index(fields=['date'], name='StockGarden_date_7e1289_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['product_name'], name='StockGarden_product_853dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['imei'], name='StockGarden_imei_063144_idx'),
        ),
        migrations.AddIndex(
            model_name='salesvoucher',
            index=models.Index(fields=['voucher_number'], name='StockGarden_voucher_cb1a06_idx'),
        ),
        migrations.AddIndex(
            model_name='salesvoucher',
            index=models.Index(fields=['date'], name='StockGarden_date_5f0d91_idx'),
        ),
        migrations.AddIndex(
            model_name='salesitem',
            index=models.Index(fields=['imei'], name='StockGarden_imei_248489_idx'),
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
