# Generated by Django 5.1.5 on 2025-03-26 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0002_repairinvoice_notes_salesinvoice_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='repairinvoice',
            name='invoice_number',
            field=models.CharField(max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
