# Generated by Django 5.1.4 on 2025-02-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0002_alter_invoice_payment_method_alter_invoice_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Cash on Hands', 'Cash on Hands'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('Pending', 'Pending')], db_index=True, max_length=255),
        ),
    ]
