# Generated by Django 5.1.4 on 2025-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0002_alter_repair_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa'), ('Cash on Hands', 'Cash on Hands')], db_index=True, max_length=255),
        ),
    ]
