# Generated by Django 5.1.5 on 2025-06-11 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Daybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('repair', 'Repair'), ('payment_received', 'Payment Received'), ('payment_made', 'Payment Made'), ('return', 'Return')], max_length=20)),
                ('reference_id', models.CharField(max_length=50)),
                ('reference_model', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], max_length=20, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], max_length=20, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daybook Entry',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='StockGarden_date_efbd2f_idx'), models.Index(fields=['transaction_type'], name='StockGarden_transac_d37b8a_idx'), models.Index(fields=['reference_id'], name='StockGarden_referen_e3ef44_idx')],
            },
        ),
    ]
