# Generated by Django 5.1.5 on 2025-04-08 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0002_alter_purchase_product_name_alter_sales_paid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='StockGarden.product'),
        ),
    ]
