# Generated by Django 5.1.5 on 2025-06-11 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0003_daybook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cashbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('entry_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment')], max_length=10)),
                ('source_type', models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('repair', 'Repair'), ('return', 'Return'), ('other', 'Other')], max_length=10)),
                ('reference_id', models.CharField(max_length=50)),
                ('reference_model', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_payment', 'Mobile Payment'), ('other', 'Other')], max_length=20)),
                ('is_bank', models.BooleanField(default=False)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashbook Entry',
                'ordering': ['-transaction_date', '-date'],
                'indexes': [models.Index(fields=['transaction_date'], name='StockGarden_transac_e8f46a_idx'), models.Index(fields=['entry_type'], name='StockGarden_entry_t_fb94b4_idx'), models.Index(fields=['payment_method'], name='StockGarden_payment_883949_idx'), models.Index(fields=['is_bank'], name='StockGarden_is_bank_b91389_idx')],
            },
        ),
    ]
