# Generated by Django 5.1.5 on 2025-04-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0003_alter_sales_paid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='expiring_date',
        ),
        migrations.AlterField(
            model_name='repairinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
