# Generated by Django 5.1.5 on 2025-06-23 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0003_alter_ledgerentry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Ledger Entry', 'verbose_name_plural': 'Ledger Entries'},
        ),
        migrations.AlterModelOptions(
            name='profitandloss',
            options={'ordering': ['-end_date'], 'verbose_name': 'Profit and Loss Statement', 'verbose_name_plural': 'Profit and Loss Statements'},
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='current_assets',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='current_liabilities',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='equity',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='fixed_assets',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='long_term_liabilities',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='other_assets',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='retained_earnings',
        ),
        migrations.RemoveField(
            model_name='cashbook',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='cost_of_goods_sold',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='gross_profit',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='net_profit',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='operating_expenses',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='other_expenses',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='other_revenue',
        ),
        migrations.RemoveField(
            model_name='profitandloss',
            name='sales_revenue',
        ),
        migrations.RemoveField(
            model_name='stockledger',
            name='created_at',
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
