# Generated by Django 5.1.4 on 2025-01-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0003_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Esewa', 'Esewa'), ('Bank Transfer', 'Bank Transfer'), ('Cash on Hands', 'Cash on Hands'), ('Khalti', 'Khalti')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('Pending', 'Pending')], db_index=True, max_length=255),
        ),
    ]
