# Generated by Django 5.1.4 on 2024-12-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0003_account_ledger_alter_invoice_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='account',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='note',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='note',
            name='party',
        ),
        migrations.RemoveField(
            model_name='notedetail',
            name='note',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='voucherdetail',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='brand',
            name='image',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Esewa', 'Esewa'), ('Cash on Hands', 'Cash on Hands')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('Pending', 'Pending')], db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='JournalEntry',
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteDetail',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
        migrations.DeleteModel(
            name='VoucherDetail',
        ),
    ]
