# Generated by Django 5.1.5 on 2025-04-08 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0003_alter_sales_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='StockGarden.product'),
        ),
    ]
