# Generated by Django 5.1.5 on 2025-06-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0004_alter_ledgerentry_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Ledger Entry'},
        ),
        migrations.AlterModelOptions(
            name='profitandloss',
            options={'ordering': ['-end_date'], 'verbose_name': 'Profit and Loss', 'verbose_name_plural': 'Profit and Loss Statements'},
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='current_assets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='current_liabilities',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='equity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='fixed_assets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='long_term_liabilities',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='other_assets',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='retained_earnings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='cost_of_goods_sold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='operating_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='other_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='other_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitandloss',
            name='sales_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
