# Generated by Django 5.1.4 on 2025-01-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0004_alter_invoice_payment_method_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='media/brands_imgs/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Bank Transfer', 'Bank Transfer'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Cash on Hands', 'Cash on Hands')], db_index=True, max_length=255),
        ),
    ]
