# Generated by Django 5.1.4 on 2024-12-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0004_remove_voucher_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Full Payment', 'Full Payment')], db_index=True, max_length=255),
        ),
    ]
