# Generated by Django 5.1.4 on 2024-12-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0005_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Hands', 'Cash on Hands'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Full Payment', 'Full Payment'), ('Pending', 'Pending')], db_index=True, max_length=255),
        ),
    ]
