# Generated by Django 5.1.4 on 2025-01-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0005_brand_image_alter_invoice_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Hands', 'Cash on Hands'), ('Khalti', 'Khalti'), ('Bank Transfer', 'Bank Transfer'), ('Esewa', 'Esewa')], db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Full Payment', 'Full Payment')], db_index=True, max_length=255),
        ),
    ]
