# Generated by Django 5.1.5 on 2025-06-12 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0005_plsection_pllineitem_profitlossstatement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pllineitem',
            options={'ordering': ['order'], 'verbose_name': 'P&L Line Item'},
        ),
        migrations.AlterModelOptions(
            name='plsection',
            options={'ordering': ['order'], 'verbose_name': 'P&L Section'},
        ),
        migrations.RemoveField(
            model_name='pllineitem',
            name='details',
        ),
        migrations.RemoveField(
            model_name='profitlossstatement',
            name='is_final',
        ),
        migrations.AddField(
            model_name='pllineitem',
            name='calculation_method',
            field=models.CharField(choices=[('auto', 'Automatic from Transactions'), ('manual', 'Manual Entry'), ('formula', 'Calculated Formula')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='pllineitem',
            name='calculation_query',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pllineitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pllineitem',
            name='formula',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pllineitem',
            name='is_contra',
            field=models.BooleanField(default=False, help_text='Whether this item reduces the section total (like discounts)'),
        ),
        migrations.AddField(
            model_name='plsection',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plsection',
            name='section_type',
            field=models.CharField(choices=[('revenue', 'Revenue'), ('cogs', 'Cost of Goods Sold'), ('expense', 'Operating Expenses'), ('other_income', 'Other Income'), ('other_expense', 'Other Expenses'), ('tax', 'Taxes')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plsection',
            name='show_subtotal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='net_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='operating_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='total_cogs',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='profitlossstatement',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='pllineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profitlossstatement',
            name='calculation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profitlossstatement',
            name='end_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='profitlossstatement',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('custom', 'Custom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='profitlossstatement',
            name='start_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='plsection',
            unique_together={('statement', 'order')},
        ),
        migrations.AddIndex(
            model_name='profitlossstatement',
            index=models.Index(fields=['start_date', 'end_date'], name='StockGarden_start_d_3f82bd_idx'),
        ),
        migrations.AddIndex(
            model_name='profitlossstatement',
            index=models.Index(fields=['status'], name='StockGarden_status_19ff67_idx'),
        ),
        migrations.AddConstraint(
            model_name='profitlossstatement',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='end_date_after_start_date'),
        ),
    ]
