# Generated by Django 5.1.5 on 2025-04-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0006_company_reg_no_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], db_index=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='repairinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], db_index=True, default='Pending', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('Partial Payment', 'Partial Payment'), ('Pending', 'Pending'), ('Overdue', 'Overdue')], db_index=True, default='Pending', max_length=20, null=True),
        ),
    ]
