# Generated by Django 5.1.5 on 2025-06-12 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0006_alter_pllineitem_options_alter_plsection_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('damage', 'Damage/Loss')], max_length=20)),
                ('reference_id', models.CharField(max_length=50)),
                ('reference_model', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_quantity', models.IntegerField()),
                ('balance_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_ledger_entries', to='StockGarden.product')),
            ],
            options={
                'verbose_name': 'Stock Ledger Entry',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['transaction_date'], name='StockGarden_transac_029f0c_idx'), models.Index(fields=['product'], name='StockGarden_product_776b27_idx'), models.Index(fields=['transaction_type'], name='StockGarden_transac_0735e5_idx'), models.Index(fields=['reference_id'], name='StockGarden_referen_2afe24_idx')],
            },
        ),
    ]
