# Generated by Django 5.1.5 on 2025-06-12 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0007_stockledger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='StockGarden.product'),
            preserve_default=False,
        ),
    ]
