# Generated by Django 5.1.5 on 2025-04-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0008_alter_purchase_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='product_name',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
