# Generated by Django 5.1.5 on 2025-06-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0008_alter_sales_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plsection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='plsection',
            name='statement',
        ),
        migrations.DeleteModel(
            name='PLLineItem',
        ),
        migrations.DeleteModel(
            name='PLSection',
        ),
    ]
