# Generated by Django 5.1.5 on 2025-06-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0009_alter_plsection_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockledger',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Stock Ledger Entry', 'verbose_name_plural': 'Stock Ledger Entries'},
        ),
        migrations.RemoveIndex(
            model_name='stockledger',
            name='StockGarden_referen_2afe24_idx',
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='reference_id',
            field=models.PositiveIntegerField(),
        ),
    ]
