# Generated by Django 5.1.5 on 2025-04-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0009_alter_purchase_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='warranty',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
