# Generated by Django 5.1.5 on 2025-04-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockGarden', '0010_alter_purchase_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='warranty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
