# Generated by Django 5.1.5 on 2025-03-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=191)),
                ('address', models.TextField(blank=True, max_length=191, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=50, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=191, null=True, unique=True)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Vendor', 'Vendor')], default='Customer', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'indexes': [models.Index(fields=['full_name'], name='user_user_full_na_51ada0_idx')],
            },
        ),
    ]
