# Generated by Django 5.1.5 on 2025-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('vendor', 'Vendor'), ('seller', 'Seller'), ('customer', 'Customer')], default='Customer', max_length=12),
        ),
    ]
